# Generated by Django 4.2.1 on 2023-05-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
