# Generated by Django 4.2.1 on 2023-06-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_openport_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openport',
            name='count',
        ),
    ]
